//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.09 at 01:05:17 PM IST 
//


package il.ac.tau.cs.smlab.fsa.xml.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SimulationNodesNodeGotos_QNAME = new QName("", "gotos");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FSAEntity }
     * 
     */
    public FSAEntity createSimulation() {
        return new FSAEntity();
    }

    /**
     * Create an instance of {@link FSAEntity.Nodes }
     * 
     */
    public FSAEntity.Nodes createSimulationNodes() {
        return new FSAEntity.Nodes();
    }

    /**
     * Create an instance of {@link FSAEntity.Nodes.Node }
     * 
     */
    public FSAEntity.Nodes.Node createSimulationNodesNode() {
        return new FSAEntity.Nodes.Node();
    }

    /**
     * Create an instance of {@link FSAEntity.Nodes.Node.Gotos }
     * 
     */
    public FSAEntity.Nodes.Node.Gotos createSimulationNodesNodeGotos() {
        return new FSAEntity.Nodes.Node.Gotos();
    }

    /**
     * Create an instance of {@link FSAEntity.Nodes.Node.Gotos.Goto }
     * 
     */
    public FSAEntity.Nodes.Node.Gotos.Goto createSimulationNodesNodeGotosGoto() {
        return new FSAEntity.Nodes.Node.Gotos.Goto();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FSAEntity.Nodes.Node.Gotos }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gotos", scope = FSAEntity.Nodes.Node.class)
    public JAXBElement<FSAEntity.Nodes.Node.Gotos> createSimulationNodesNodeGotos(FSAEntity.Nodes.Node.Gotos value) {
        return new JAXBElement<FSAEntity.Nodes.Node.Gotos>(_SimulationNodesNodeGotos_QNAME, FSAEntity.Nodes.Node.Gotos.class, FSAEntity.Nodes.Node.class, value);
    }

}
